### ISSUE TITLE
Kafka Proxy is mangling the message.

### ISSUE THREAD

**Issue by max522over** [confluentinc/kafka-rest#112]
when I send the message this way

curl -X POST -H "Content-Type: application/vnd.kafka.v1+json"       --data '{"records":[{"value":"this is a big mess and I want this to be much longer that that other stuff"}]}' "http://130.211.148.36:8082/topics/test"
{"offsets":[{"partition":0,"offset":4,"error_code":null,"error":null}],"key_schema_id":null,"value_schema_id":null}

I get binary garbage in the consumer. When I use the producer on the kafka broker machine I get clear text.
./kafka-console-consumer.sh --zookeeper unsecure-w-1.c.prj01475-sii-0000-23340-dev.internal:2181,unsecure-m-0.c.prj01475-sii-0000-23340-dev.internal:2181,unsecure-w-0.c.prj01475-sii-0000-23340-dev.internal:2181 --topic test --from-beginning
???ƛ?	??Ƨt???a??hm?rh????????^??n
this is a test
so it's not mangled
ok that bothers me.
???ƛ?	??Ƨt???a??hm?rh????????^??n
???ƛ?	??Ƨt???a??hm?rh????????^??n

**Comment by ewencp** [comment]
This looks like it's probably correct behavior -- when you produce via the REST API, the data you pass to the `"key"` and `"value"` fields needs to be encoded properly for the *embedded format*. See the discussion under the [Content Types](http://docs.confluent.io/1.0.1/kafka-rest/docs/api.html#content-types) section of the REST API documentation.

In this case, the strings you're sending are being decoded as base64, which is why they are turning into garbage.

Having the base64 encoding is necessary to support arbitrary binary payloads. We could possibly add something like the equivalent of the StringSerializer, which would only support strings (encoded directly) rather than arbitrary binary data, although I'm not sure how many people have a use case for that -- usually people need to store more complex data than just an UTF-8 string.

**Comment by max522over** [comment]
I did create a consumer via rest proxy and then did a get against that consumer and I got back the text I sent it. So I see that the proxy is encoding as you say and I assume also putting it into some format that a consumer will need to process. We currently send around 30K messages a minute in our current kafka system. Our current producer is a java set of classes in our Mule ESB. But we are going to need to open that up to producers that will not be java based, thus the exploration of a rest interface. Our consumer is a storm spout in java. I think I need to understand better  what I will need to do on that consumer side to convert the message to the format our bolts expect. Right now it's just a big blob of json that we store and also process into a format that can be used for analysis later. Do you have some code that I should look at as an example of how to consume it in general right out of kafka.

**Comment by max522over** [comment]
Thank you for your quick response.

**Comment by ewencp** [comment]
@max522over In Kafka, the data will be stored as raw bytes. The binary mode of the REST proxy just writes a `byte[]`, as if using the `ByteArraySerializer` in Kafka. However, in order to embed a `byte[]` in the JSON request (which your application sends) or the JSON response (which the REST proxy sends when you read from a topic with a consumer), it needs to encode it because not all bytes can be included in strings directly. This is where the base64 encoding comes in.

In your original example you were trying to produce the string `this is a big mess and I want this to be much longer that that other stuff` (presumably UTF-8 encoded) to the topic. To do so, you need to base64 encode that string in the request, like this:

```
curl -X POST -H "Content-Type: application/vnd.kafka.v1+json" --data '{"records":[{"value":"dGhpcyBpcyBhIGJpZyBtZXNzIGFuZCBJIHdhbnQgdGhpcyB0byBiZSBtdWNoIGxvbmdlciB0aGF0IHRoYXQgb3RoZXIgc3R1ZmY="}]}' "http://130.211.148.36:8082/topics/test"
```

The REST proxy does the base64 decoding and then produces those decoded bytes (which will just be the UTF-8 string) to Kafka. When you consume via the REST proxy, it reads the raw data, base64 encodes it, and places it in the response JSON. Since the data is stored in raw form in Kafka, any other consumer should be able to consume it normally. You should not need to do anything special with the Storm spout.

For your use case with JSON, you would do exactly the same thing since the JSON is just UTF-8 text. Take the JSON serialized as a string, base64 encode, and set it as the `value` field in your request.

I'm going to close this as I don't think there's an issue to fix here, but feel free to reopen if you think there is, and of course follow up with any additional questions.

**Comment by max522over** [comment]
Very informative. Thank you!
