### ISSUE TITLE
Kafka rest uses vulnerable dependency CVE-2023-44981

### ISSUE THREAD

**Issue by omersivrikaya** [confluentinc/kafka-rest#1209]
Version 3.9.1, 3.8.3, or 3.7.2 which are all versions of ZooKeeper containing a fix for this issue.

https://www.instaclustr.com/blog/security-advisory-cve-2023-44981-apache-zookeeper/

**Comment by reimgun** [comment]
our scanner found the same:

in Version 7.5.2

CVE | SEVERITY | CVSS | PACKAGE | VERSION | STATUS | PUBLISHED | DISCOVERED | DESCRIPTION | TRIGGERED FAILURE
-- | -- | -- | -- | -- | -- | -- | -- | -- | --
CVE-2023-44981 | critical | 9.10 | org.apache.zookeeper_zookeeper | 3.6.3 | fixed in 3.9.1, 3.8.3, 3.7.2 | 29 days | < 1 hour | Authorization Bypass Through User-Controlled | Yes

**Comment by janjwerner-confluent** [comment]
This has been resolved in q4 2023.
