### ISSUE TITLE
{"error_code":415,"message":"HTTP 415 Unsupported Media Type"}

### ISSUE THREAD

**Issue by tanmay-lumiata** [confluentinc/kafka-rest#129]
I downloaded the latest platform confluent-1.0.1. And was trying REST APIs. But I could only see GET APIs working. I am not able to send message to specific topic. 

I am trying samples from this page http://docs.confluent.io/1.0.1/kafka-rest/kafka-rest/docs/intro.html#kafkarest-intro

Request 
<code> curl -X POST -H "Content-Type: application/vnd.kafka.json.v1+json" --data '{"records":[{"value":{"foo":"bar"}]}' "http://localhost:8082/topics/test1" </code>

Response 
<code> {"error_code":415,"message":"HTTP 415 Unsupported Media Type"} </code>

I have topic test1 created.

**Comment by ewencp** [comment]
First, JSON wasn't added as an embedded format until after version 1. It will be available as part of Confluent Platform with the next release. The path in the URL also doesn't look right (note how `kafka-rest` is in there twice and if you navigate to the quickstart from the front page of the docs you'll end up at http://docs.confluent.io/1.0.1/kafka-rest/docs/intro.html#quickstart), so I think you stumbled upon a stray extra file that snuck in somehow. (@miguno, you might want to look into that stray file since it probably got in as a leftover during the docs build + deploy process.)

So the response code is accurate since the `application/vnd.kafka.json.v1+json` type is not supported in that version of the server.

However, it looks like there's a minor typo in the quickstart. It's missing a `}`. The current payload is:

`{"records":[{"value":{"foo":"bar"}]}`

but it should be

`{"records":[{"value":{"foo":"bar"}}]}`

**Comment by miguno** [comment]
@ewencp wrote:
> (@miguno, you might want to look into that stray file since it probably got in as a leftover during the docs build + deploy process.)

Yeah, there were indeed some duplicate files which contained outdated docs, which I just removed; for reference:

```
1.0.1/_sources/camus/camus/
1.0.1/_sources/kafka-rest/kafka-rest/
1.0.1/_sources/schema-registry/schema-registry/
1.0.1/camus/camus/
1.0.1/kafka-rest/kafka-rest/
1.0.1/schema-registry/schema-registry/
```

I did a quick post-mortem but could not determine what could have caused this -- the docs build pipeline looked/looks fine.
