### ISSUE TITLE
post message to an undefined topic result with a 50003 error code

### ISSUE THREAD

**Issue by inadler** [confluentinc/kafka-rest#133]
In my Kafka Broker configuration I set the `auto.create.topics.enable` to false.
Now, when I post a message to an undefined topic, the request hangs for about two minutes and returns with error code 50003 (instead of 404 Not Found)

Below is an example of the response (please notice the "28ms" which is also wrong)

{
  "offsets":[ {
    "partition":null,
    "offset":null,
    "error_code":50003,
    "error":"Failed to update metadata after 28 ms."
  }],
  "key_schema_id":null,
  "value_schema_id":null
}

**Comment by ewencp** [comment]
Unfortunately, there's not much we can do about this -- it's the drawback of having auto topic creation and it being optional. We don't get enough info back from brokers to tell whether we can fail fast (auto topic creation isn't enabled so the topic won't be created) or if waiting and retrying will work (auto topic creation is enabled).

I agree the error message isn't ideal, but it's tied to the *last* error generated and passed back to the producer. We could possibly catch exceptions specifically tied to metadata errors like this one, but even that is tough -- we actually get a TimeoutException in this case, which could be caused by a variety of issues.
