### ISSUE TITLE
Delete consumer does not reset offsets

### ISSUE THREAD

**Issue by neerajBaji** [confluentinc/kafka-rest#134]
- Create a consumer instance
- Read from a topic
- Delete the consumer instance
- Create consumer instance with the same consumer group and instance id as before
- Read from a topic

I would expect the final step to return all messages from the said topic since its a new consumer; instead it returns an empty list.

Listing offsets from the recreated consumer also returns an empty list.

Regards,
Neeraj

**Comment by ewencp** [comment]
@neerajBaji This is the expected (and important!) behavior of consumers. Consumers in kafka-rest are implemented using the normal Java consumers. Offsets are persisted by consumer group, which allows a) multiple consumers to coordinate and when they rebalance partitions, they can tell where a different instance left off and b) even if all your consumer instances fail, you can resume processing from where you left off.

There is a tool included with Kafka called `kafka-consumer-groups.sh`. You can use that to delete the state associated with the consumer *group* so that if you started new instances in the group, they would start reading the topic from scratch (assuming you have them configured to reset to the earliest offset).

**Comment by neerajBaji** [comment]
@ewencp Thanks a lot for the detailed answer. Helped clear out my doubts.

**Comment by WalterDalton** [comment]
Can we have the ability to delete Consumer Groups in Kafka Rest?

**Comment by inadler** [comment]
So what is the meaning of the "offset commit" operation? when does it come into use?

**Comment by premshree** [comment]
Hey @ewencp I was trying to use `kafka-consumer-groups.sh` to delete group metadata, using `--new-consumer`. The tool doesn't let me delete if I use that flag. What are my options if I want new consumers to start from scratch (based on whether they are configured to read offset earlier, or offset newest)? Thank you!

**Comment by ewencp** [comment]
@JohnOmernik Yeah, that'd basically be the equivalent of deleting the group altogether in the REST API. I proposed some preliminary APIs for [admin APIs here](https://github.com/confluentinc/kafka-rest/wiki/Project---Admin-APIs), but I couldn't give you a timeline for them at the moment.

@premshree This isn't related to the current functionality of kafka-rest since it doesn't use the new consumer yet, but the new consumer doesn't have quite the same semantics. Strictly speaking, you don't need to delete offsets directly because to delete them assumes the group is empty, in which case you can join the group as the only member and do whatever you want to the offsets (e.g. commit whatever values you want). I think this may be more explicitly added as an admin API (see KIP-4), although I don't think there are concrete plans for that yet.

**Comment by premshree** [comment]
Thanks for your response @ewencp. I wasn't sure what the right forum to ask this might be.
