### ISSUE TITLE
Dangerous constructor in io.confluent.kafkarest.entities.BinaryTopicProduceRecord

### ISSUE THREAD

**Issue by lukemao** [confluentinc/kafka-rest#141]
The reason I think this is a defect is that in the class io.confluent.kafkarest.entities.BinaryTopicProduceRecord

One of the constructors in the class is:

  public BinaryTopicProduceRecord(byte[] value) {
    this(null, value, null);
  }

The use can mistakenly create a ProduceRecord with a key as parameter.

**Comment by ewencp** [comment]
@lukemao I agree there is a small risk of misuse, but this isn't public API and it is pretty standard to allow for a version that doesn't include a key since many use cases don't have keys at all. See, for example, the [equivalent ProducerRecord constructor](http://docs.confluent.io/2.0.0/clients/javadocs/org/apache/kafka/clients/producer/ProducerRecord.html#ProducerRecord%28java.lang.String,%20V%29).

**Comment by lukemao** [comment]
@ewencp thank you for the message.

**Comment by lukemao** [comment]
@ewencp thanks for the message. I agree with you too.
