### ISSUE TITLE
Where is the REST request body json is parsed

### ISSUE THREAD

**Issue by lukemao** [confluentinc/kafka-rest#142]
It looks like the json is parsed by Jackson into JsonTopicProduceRecord. Where does this take place?

**Comment by ewencp** [comment]
@lukemao This is handled by the Jersey framework, which manages all the common HTTP request processing. Since Jersey supports different request entity formats, we specify that it should use [`JacksonMessageBodyProvider`](https://github.com/confluentinc/rest-utils/blob/master/core/src/main/java/io/confluent/rest/validation/JacksonMessageBodyProvider.java). You can look at that class for details, but it's mostly implemented by its superclass, `JacksonJaxbJsonProvider` which is from the `jackson-jaxb-json-provider` library. It knows to deserialize a `JsonTopicProduceRecord` because it is specified as an argument to the `TopicsResource.produceJson` method.

**Comment by lukemao** [comment]
Sure, I will have a look, may ping you for further questions :)
