### ISSUE TITLE
rest stream limit 

### ISSUE THREAD

**Issue by lushuai2013** [confluentinc/kafka-rest#146]
How to control the all request total stream speed,  I test the rest server bu catnot find the limit speed  configuration.

**Comment by ewencp** [comment]
The REST server doesn't include this. However, Kafka itself [supports quotas as of 0.9](http://kafka.apache.org/documentation.html#design_quotas). Since producer and consumer settings are passed through the REST server config to the instantiated producer and consumer, you can configure it just as you would a normal client to set the `client.id`. Then you just configure the broker as appropriate.

Note, however, that this currently only gives you control over the rate for the entire REST proxy. If you need different rates applied to different clients, it would require changes to the proxy code.

**Comment by lushuai2013** [comment]
thanks.   but the rest serer has limit speed  after I tested many times , when i use multer threads to transport the data to the server,  the total high speed is 30MB/s ,  I think  maybe the jetty configration limit the speed.   for exapmle : jetty threads , buffersize .
