### ISSUE TITLE
GET on consumers with several hundreds topics created 

### ISSUE THREAD

**Issue by chrisramond** [confluentinc/kafka-rest#154]
After running some load tests using the kafka-rest api , i found responses times from 3s till 30s when trying to get messages from a topic using a the uri of consumer previously created.

25 topics tested among 800 created 
20000 messages of 3,5k posted to each of the 25 topics
A consumer is created after 10000th message is posted for each topic .
The uri returned on the consumer creation is used to get the messages of each topics. ( max_bytes = 1000000 )

Setting the consumer.request.timeout.ms to 100 and consumer.threads to 25 does not change anything.

If the unused topics are deleted ( 25 topics kept only ) , the response time is around 1s.

**Comment by ewencp** [comment]
I think this is due to trying to load all the metadata when checking if the topic exists. I think there are further improvements that could be made (e.g. some caching of topics in `MetadataObserver`), but #202 should have improved this substantially. I'm going to close this out, but if you reevaluate and find the performance is still poor, please reopen and we can work on it from there.
