### ISSUE TITLE
Error messages contain "or" 

### ISSUE THREAD

**Issue by aragnon** [confluentinc/kafka-rest#179]
The topic "avrotest" exists. Then I use your example code:

```
#!/bin/sh

curl -i -X POST -H "Content-Type: application/vnd.kafka.avro.v1+json" --data '{"value_schema": "{\"type\": \"record\", \"name\": \"User\", \"fields\": [{\"name\": \"username\", \"type\": \"string\"}]}","records": [{"value": {"username": "testUser"}}, {"value": {"username": "testUser2"}}]}' http://localhost:8082/topics/avrotest
```

As a result I get the following useless error message:
`{"error_code":40801,"message":"Schema registration or lookup failed"}`

Giving an error message in the form of an "or" is either just malicious programming or extremely incompetent programming. I am not sure which one you were aiming for, but I do not like it. 

I will likely figure out what the issue is myself, but I'd like some developer to tell me before that happens.

**Comment by ewencp** [comment]
@aragnon The request to the schema registry failed for some reason (e.g. the service is not running on the host & port specified in the REST Proxy configuration). We use "or" here because the failure means it is impossible to differentiate between a new registration (schema has never been registered with the schema registry) and a lookup of an existing ID (the schema has already been registered on the corresponding schema registry subject).

**Comment by aragnon** [comment]
I do not agree that it is impossible to differentiate between those cases, because in this case it's all running on the same machine, which is also typical for a development setup (and which will probably be the first thing people try to do). Additionally, there could be additional information channels, and this too could be made more user friendly. 

There are some things which are impossible; this isn't one of them.
