### ISSUE TITLE
Maximum size per message or request?

### ISSUE THREAD

**Issue by bambamx** [confluentinc/kafka-rest#190]
Hi does somebody knows whats the maximum size per message or request that kafka rest can handle? I'm having issues with large messages

**Comment by ewencp** [comment]
The `max_bytes` parameter on [consumer read requests](http://docs.confluent.io/3.0.0/kafka-rest/docs/api.html#get--consumers-(string-group_name)-instances-(string-instance)-topics-(string-topic_name)) will partially control this, but defaults to unlimited (`Long.MAX_VALUE`). There is also `consumer.request.max.bytes` for the REST proxy config, which defaults to 64MB. There are 2 configs because they are controlled by different people -- the former by the user of the REST proxy, the latter by the operator of the proxy, and they may have different constraints they want to apply. The actual limit in the REST proxy is the min of these two values.

However, it'll also be affected by the underlying consumer settings [which can be overridden in the REST proxy config](http://docs.confluent.io/3.0.0/kafka-rest/docs/config.html#configuration-options) as well as broker configs (`message.max.bytes` for the broker-wide config and `max.message.bytes` for the topic-level config). The default for the Kafka broker and Java clients is 1MB. 

I'm going to close this as it was just a question, but if you're still running into issues and it looks like you've updated the relevant limits on all the components, please feel free to reopen and add more detail to the original question.

**Comment by divyesh2506** [comment]
Hi, @ewencp is there a maximum size limit for POST requests. I am getting JsonParseException with large size of JSON POST data for being produced to a certain kafka topic.

**Comment by axisc** [comment]
@divyesh2506 POST itself has very large limits. The JsonParseException may be due to configuration for your REST proxy.
