### ISSUE TITLE
Where to set the max.poll.records configuration

### ISSUE THREAD

**Issue by bryancrosby** [confluentinc/kafka-rest#209]
Trying to utilize the functionality of the new ([here](https://issues.apache.org/jira/browse/KAFKA-3007) and [here](http://docs.confluent.io/3.0.0/release-notes.html#apache-kafka-0-10-0-0)) `max.poll.records` feature in 0.10 - is there support from the REST proxy for this yet?

**Comment by ewencp** [comment]
@bryancrosby The REST proxy has not been converted to the new consumer yet, so the `max.poll.records` would not work for it. When it is converted, support for the option will be automatic in the sense that config options are passed through from the REST proxy config to producers/consumers (see [description here](http://docs.confluent.io/3.0.0/kafka-rest/docs/config.html#configuration-options)), but depending on the implementation we end up with for the new consumer support it may not directly do what you expect since the REST proxy wraps the consumer and does its own batching management to encourage better batching behavior which is important for the REST proxy to get good throughput.

**Comment by hivie7510** [comment]
Would this be a relatively simple task?  Or have the signatures changed significantly?

**Comment by ewencp** [comment]
Definitely non-trivial, the new consumer and old consumer have very different APIs. Adding the new consumer also requires thinking through compatibility issues and maintaining parallel support for the old and new consumer (so people have a migration path). None of this is spectacularly difficult, but not an hour long project.

**Comment by alexlod** [comment]
There's an open issue for switching to the new consumer if you'd like to follow along: https://github.com/confluentinc/kafka-rest/issues/204

**Comment by nucknorris** [comment]
Now that the new consumer API is implemented, I'm still not able to use `max.poll.records`. When I send it via REST I get `Unrecognized field: max.poll.records`. Is there any other way?

**Comment by luxin88** [comment]
is rest server support for this configuration yet?
