### ISSUE TITLE
consumer group problem

### ISSUE THREAD

**Issue by nathan-zhu** [confluentinc/kafka-rest#213]
Hi, follow this like [#211](https://github.com/confluentinc/kafka-rest/issues/211)

i try to get consumer group to test, will keep the instances keep alive, 

`  curl -X POST -H "Content-Type: application/vnd.kafka.v1+json" 
--data '{"name": "consumer_1", "format": "json", "auto.offset.reset": "smallest","auto.commit.enable": "false"}' 
http://10.216.90.225:8082/consumers/testgroup/`
`   curl -X POST -H "Content-Type: application/vnd.kafka.v1+json" 
--data '{"name": "consumer_2", "format": "json", "auto.offset.reset": "smallest","auto.commit.enable": "false"}' 
http://10.216.90.225:8082/consumers/testgroup/`

all message default assign to partition0 test it working well , but after default 5 minutes all instances get destroy again. 

` curl -X GET -H "Accept: application/vnd.kafka.json.v1+json" http://10.216.90.225:8082/consumers/testgroup/instances/consumer_1/topics/test1
{"error_code":40403,"message":"Consumer instance not found."}%`

i try to revive the instance i recreate same consumer again. 

`  curl -X POST -H "Content-Type: application/vnd.kafka.v1+json" 
--data '{"name": "consumer_1", "format": "json", "auto.offset.reset": "smallest","auto.commit.enable": "false"}' 
http://10.216.90.225:8082/consumers/testgroup`

i get all message from beginning again. i'm newer for kafka, should i do other way to get it working?

please help me ,thanks.

**Comment by ewencp** [comment]
I'm not sure I understand what you're referring to with

> all message default assign to partition0 test it working well

but the behavior you see where you are getting all messages again from the beginning is due to using `auto.offset.reset=smallest` (reads from the beginning if no committed offset is available), `auto.commit.enable=false` (your consumers current position will never be committed automatically), and I'm guessing you are never [committing offsets](http://docs.confluent.io/3.0.0/kafka-rest/docs/api.html#post--consumers-(string-group_name)-instances-(string-instance)-offsets). Reviewing the [delivery semantics](http://kafka.apache.org/documentation.html#semantics) might help clarify how tracking which data has been consumed works in Kafka. You need to commit offsets, i.e. `POST` to the `offsets` resource for your consumer instance, periodically to record your progress with processing messages.

**Comment by nathan-zhu** [comment]
@ewencp thanks for explain it patiently, i will try to update commit to enabled, please keep it open will come back soon. by the way, for stupid questions. how to revive instances for alive consumer?

**Comment by ewencp** [comment]
> how to revive instances for alive consumer?

Not sure what you're asking. Are you asking what to do if the instance on the REST proxy dies but the client was just busy processing the data from the previous fetch, so it wants to recreate the instance on the REST proxy? You can just recreate it as you normally would -- there's no special procedure for recreating a consumer instance.

**Comment by nathan-zhu** [comment]
yes, that's what i want to asked question, sorry , my english is pool.

i will test to recreate instance, thanks.

**Comment by nathan-zhu** [comment]
@ewencp after add auto.commit.enable=true and recreate instance working well for single or group consumers. 
another question, is there can assign partition during create topic with api? i didn't found document for it. 

if not support should i do it with command line then use it?

**Comment by ewencp** [comment]
@nathan-zhu There is not currently an API for creating topics via the REST proxy. You would do that via the command line tools.
