### ISSUE TITLE
Avro ? JSon ? or Binary ? messages on a topic  

### ISSUE THREAD

**Issue by Antwnis** [confluentinc/kafka-rest#220]
At the moment when creating a consumer through *kafka-rest* for a particular *topic* i have no idea a priori on whether i will need the `avro | json | binary` 🎱 

So we have to blindly create 3 consumer in turn, until one of them succeeds
 
    application/vnd.kafka.avro.v1+json
    application/vnd.kafka.v1+json
    application/vnd.kafka.binary.v1+json

Visibility on the type would be helpful

**Comment by ewencp** [comment]
@Antwnis This problem implies that you are not sure which one of these formats will succeed. If *you* don't know which one will be successful, it isn't really possible for the REST proxy to have any idea either. In general, you should know the format of data in each Kafka topic.

We would highly recommend standardizing on a single serialization format per topic, and even better would be standardizing on both the serialization format *and* a way to determine what data is in a given topic. One good way of doing that is using [Avro and the schema registry](http://docs.confluent.io/3.0.0/schema-registry/docs/intro.html) to track this format, but even if you use a different format, it would be best to choose a single format or at least define elsewhere what format each topic will use.

Please note that some cases, like the `application/vnd.kafka.binary.v1+json` case you mentioned, will be catch-all cases -- by definition they can correctly convey all other formats, so if you are trying to detect the "correct" version using formats like these, you will not get the expected result; they will capture all other formats.

**Comment by Antwnis** [comment]
As said we can use the schema registry to track the format itself.

What is troubling me is tracking which topic uses a particular schema (or subject).

All i can think of is:

    if ${TOPIC}-value exists in schema-registry
        // Assume that this topic `most probably` uses the above value schema
    if (${TOPIC)-key exists
        // Assume that this topic `most probably` uses the above key schema

Could an endpoint reveal such information ? Can one easily find out that : 

* **connect-configs** - is **binary**
* **_schemas** - is **json**
* **topicX** is **avro** with value schema id **x** (subject =  topicX-value)

The tricky part that i don't see a solution to - is understanding how topics map to particular schemas.
Having that knowledge would be helpfull.

**Comment by ewencp** [comment]
@Antwnis There is no way to know this unless you standardize within your organization. Most of the topics you listed are actually special cases as they are really internal to other systems, not your own data (`connect-configs` is internal to Connect, `_schemas` is internal to the schema registry). Since anyone could potentially produce data directly to Kafka, there is no *guarantee* you can determine all of this from the schema registry.

However, if you standardize on always using Confluent's Avro serializers and converters, then all data other than Kafka internal topics (e.g. `__consumer_offsets`) and the schema registry (which can't rely on its own functionality so needs to make some assumptions about data format, which we do via careful use of JSON) will have info in the schema registry about their format. We will stick to the topic -> subject mapping where we just append `-key` and `-value` to the topic name, so the pseudocode you included above will be a reliable way of checking the schema.

Kafka itself does not do any filtering by format and in fact the broker knows nothing about the serialization format -- serializers (and converters in Connect) are really just conveniences for the user. All Kafka ever sees (and stores, and processes) is the resulting `byte[]`.

**Comment by Antwnis** [comment]
Thank you @ewencp happy to resolve this issue

**Comment by Antwnis** [comment]
Took me a while to get there, but that's where i wanted to use it for 
https://kafka-topics-ui.landoop.com
