### ISSUE TITLE
Feature : Message Listener(that can hit callback registered)

### ISSUE THREAD

**Issue by jacksparrrow** [confluentinc/kafka-rest#224]
Please find Details here.
https://issues.apache.org/jira/browse/KAFKA-3970

**Comment by ewencp** [comment]
@jacksparrrow That's kind of the reverse (push instead of pull) of the REST proxy's design. This actually sounds perfectly suited for a [Kafka Sink Connector](http://docs.confluent.io/3.0.0/connect/intro.html) -- the connector would just accept data from Kafka and then try to hit the webhook with the data.

**Comment by jacksparrrow** [comment]
Hi @ewencp
I am building this component on top of kafka 0.10 as per our use case.
Can you guide me how to contribute the same to kafka source.

**Comment by ewencp** [comment]
@jacksparrrow No need to get it into Kafka itself. For connectors we use a federated approach because it's not really practical to pull all the connectors into Kafka. Instead, we maintain the core framework and runtime there, but connectors live in their own repositories. For a bunch of examples, check out the [connector hub](http://connectors.confluent.io). We also have [documentation](http://docs.confluent.io/3.0.0/connect/devguide.html) explaining how to get started building connectors. If you have any specific questions or trouble getting started, let me know.

**Comment by jacksparrrow** [comment]
@ewencp 
This is how i interpreted (correct me if wrong)
Kafka Connect:
	Integrating Data-sources directly (db, file system..etc) generally falls under ETL or can be    
        extended to streaming(no ETL)  
Rest Proxy:pull
	**Integrating services**(pull mechanism) serving biz logic on top of these services
	
	My thought is, Is it good to have push mechanism also in Integrating services.
	e.g	after payment event is done call order service (POST) to create order and do some business
        logic	its like integrating services(business) that provide basic CRUD operations. Service need not   
        to bother how they are orchestrated

	As compared to Rest Proxy internal threads will do processing based on-demand http connection 
        (pull) In my case(push) one thread is dedicated for each such connection that keeps on polling 
        and do push.100's of service orchestration need 100 such threads (this can be made fault tolerant   
        using akka )
	Timeout logic of kafka client can be used to stop and restart listener after some backoff. 
	I am calling it some kind of event bus.
 
Suggest me if this is good way to go or the same thing can be achieved using kafka + confluent modules as i just started scratching surfaces of these.

**Comment by ewencp** [comment]
@jacksparrrow I'm not sure about the internal implementation of it, but I was just suggesting that a sink connector could fit your model and naturally allows for scaling up to the number of partitions you are consuming from. How you manage making each request to the destination system probably depends on the performance characteristics of that system (e.g. what is the latency? does it depend on ordering? does it support batching multiple messages into a single request?). But the simplest implementation could be as simple as taking each message that is `put()` to the sink connector's task and makes a synchronous HTTP request to your webhook. More complex implementations could take advantage of async requests (whether by threads or a natively async API), batching, etc.

**Comment by jacksparrrow** [comment]
Thanks @ewencp for the valuable inputs..I will explore the connector's api for my use case.
