### ISSUE TITLE
Produce Preformatted JSON Message

### ISSUE THREAD

**Issue by sukhdeepsinghkohli** [confluentinc/kafka-rest#225]
Hello Team,

I am looking a waay to setup Producer to drop a preformatted complex JSON into a KAFKA topic but everytime I hit, it gives 422 error.

Is there something I am missing

**Comment by ewencp** [comment]
If you're sending JSON it isn't guaranteed to preserve the formatting since we parse it with Jackson to extract the individual messages and then serialize the individual messages.

If you want to preserve formatting precisely, you're going to want to produce the binary data directly, i.e. serialize the JSON yourself, base64 encode to ensure you preserve the exact data, and produce binary data using the Content-Type `vnd.kafka.binary.v1+json`.

If you're hitting a 422, it indicates that the server can't parse your payload or it doesn't have the expected structure. If you include an example payload and the error message (if any more extensive message is returned), we might be able to spot the issue with your request.

**Comment by sukhdeepsinghkohli** [comment]
Thanks! This can be closed. I missed the part of base64 encoding it when using Binary
