### ISSUE TITLE
How to consume messages again in 3.0

### ISSUE THREAD

**Issue by nathan-zhu** [confluentinc/kafka-rest#226]
hi, i build on 3.0, is there any way to repeat consume messages，have some questions at below.
1.  Is confluent3.0 support consume confirm method?
2. How to reused message again if i needed?  I only thought way like that resend message to kafka again. but feeling it more stupid, is that have other way do it? thanks.

**Comment by ewencp** [comment]
@nathan-zhu With the regular clients your options are to either seek to whatever offset you want to start reconsuming at or use another consumer group. At the moment the proxy doesn't support seeking, so you'd have to use another consumer group to reprocess data.

I'm not sure what you mean by "consume confirm method", but I think you may be referring to offset commit, which persists the offset you're currently at so even if your process crashes it can pick up where it left off. That's supported in the [consumer API](http://docs.confluent.io/3.0.0/kafka-rest/docs/api.html#post--consumers-(string-group_name)-instances-(string-instance)-offsets).

For reusing messages, Kafka is a pub-sub system. Just because one consumer reads a message doesn't mean that message is deleted. So you don't need to send the data to Kafka again, you can just consume it again (either via seeking or with a new consumer group).
