### ISSUE TITLE
Redundant setting for SSL communication to broker?

### ISSUE THREAD

**Issue by simplesteph** [confluentinc/kafka-rest#283]
http://docs.confluent.io/3.2.0/kafka-rest/docs/config.html#configuration-options-for-ssl-encryption-between-rest-proxy-and-apache-kafka-brokers

If listeners are set to `SASL_SSL://` or `SSL://`, shouldn't the rest proxy figure out the value for `client.security.protocol` ?

**Comment by ewencp** [comment]
@simplesteph `listeners` and `bootstrap.servers` don't have to have the same format -- in particular `bootstrap.servers` is generally just a list of `host:port` pairs (and even with included protocol info, depending on how you discover your bootstrap servers and if you listen with different security protocols on different brokers, you still might need the `client.security.protocol` to filter down to listeners returned in metadata requests that match).

The `clients.` settings are just being forwarded to the underlying producer/consumer, so these settings are being inherited from Kafka's producer/consumer. It is valid to have something like `bootstrap.servers=host1:9092,host2:9092` and `client.security.protocol=SASL_SSL`.

**Comment by simplesteph** [comment]
Interesting! Is there too flexibility in `bootstrap.servers`, allowing both `protocol://host:port` and `host:port`

@ewencp then there might be a few typos in the doc, which might lead to confusion?
![image](https://cloud.githubusercontent.com/assets/20851561/24635770/0a40be36-1919-11e7-88fb-a42921c3b01a.png)
![image](https://cloud.githubusercontent.com/assets/20851561/24635783/1ceeedaa-1919-11e7-8ce3-a3758ce3969e.png)

**Comment by ewencp** [comment]
To clarify, it's actually gotten even a bit more complex with [KIP-103](https://cwiki.apache.org/confluence/display/KAFKA/KIP-103%3A+Separation+of+Internal+and+External+traffic) -- now you can distinguish between a *listener name* and the security protocol used (which allows you to do things like distinguish between internal and external traffic, isolate to different nics, etc). What you specify in `security.protocol` (or the `producer.`, `consumer.`, or `client.` prefixed version in REST proxy should match the bootstrap broker `host:port` settings you have since clients will only use a single security protocol. When it connects and gets broker info from one of the bootstrap servers, those metadata requests return only matching *listener names* (which when simplified to your case just map to the protocol names).

On the client side, you can include things in the format protocol://host:port, but the protocol part is just stripped out. However, it can be helpful for documenting what you *expect* to see from the broker. Today there is no validation done because you don't even have any information about the broker (aside from this user-specified protocol that could be wrong) until you connect to the broker. But the first thing you do is try to authenticate with the given protocol, so you don't have a chance to get that information to decide whether they properly match.

**Comment by simplesteph** [comment]
You're right it's getting complicated, nonetheless I should close this as it's a non issue. Thanks for the clarification
