### ISSUE TITLE
zookeeper is needful?

### ISSUE THREAD

**Issue by rangwea** [confluentinc/kafka-rest#287]
the zookeeper is kafka's zookeeper? or is kafka-rest's zookeeper??

**Comment by ewencp** [comment]
@rangwea The zookeeper specified is Kafka's. Although there is progress towards mostly hiding ZK from Kafka users, the REST proxy still relies on it for some functionality (and it still supports the old consumer API that requires access to Zookeeper). So this won't be a separate Zookeeper cluster, it will be the Zookeeper cluster that Kafka uses.

I'm going to close this out since it's a simple question, but feel free to reopen if more clarification is needed.

**Comment by rangwea** [comment]
@ewencp Thanks,I have already understand it by learning the source code.but thanks.
