### ISSUE TITLE
Lightweight admin APIs (create/delete/list/describe topics)

### ISSUE THREAD

**Issue by nehanarkhede** [confluentinc/kafka-rest#3]

**Comment by wanghaisheng** [comment]
how to create a topic right now ?there is no doc

**Comment by ewencp** [comment]
@wanghaisheng We have some ideas on implementing admin APIs that are commonly handled through the built-in command-line APIs for Kafka (such as create topic) which we've outlined here: https://github.com/confluentinc/kafka-rest/wiki/Project---Admin-APIs However, these are not implemented in the currently released version (or currently in `master`).

To see the current set of supported features (and a list of what we *haven't* implemented yet) check out this section of the docs: http://docs.confluent.io/1.0/kafka-rest/docs/intro.html#features

**Comment by kjvalencik** [comment]
:+1:. This is mostly useful for unit tests where you want to always create a fresh topic to ensure that you don't get stale data. Currently, we are working around this with a mix of retrying consumer create on Topic Not Exists errors and using the `kafka-node` library exclusively for admin commands.

Cheers!

**Comment by ducas** [comment]
:+1: I created #109, but have closed it as @kjvalencik pointed me at this. Here is the text -

As a client I would like to create a topic by making a request to the API so that I can specify partitions, replication factor and other configuration options.

## For Example...
### PUT /topics/(string: topic_name)
_Parameters_
* topic_name (string) - The topic to consume messages from.

_Request JSON Object_
* partitions (int) - The number of partitions the topic will have
* replication_factor (int) - The replication factor of the topic
* config (object) - The configuration to use for this topic (see [Kafka Topic Config](http://kafka.apache.org/documentation.html#topic-config) for all options)

#### Example Request
    PUT /topics/test_topic/ HTTP/1.1
    Host: kafkaproxy.example.com
    Accept: application/vnd.kafka.v1+json, application/vnd.kafka+json, application/json
    {
      "partitions": 40,
      "replication_factor": 10,
      "config": {
        "flush.ms": 50
      }
    }

**Comment by kjvalencik** [comment]
@ducas As a work around, I've been using [kafka-manger](https://github.com/yahoo/kafka-manager) for admin API.

**Comment by micahstubbs** [comment]
curious, any movement on these APIs for interacting with topics? 

`create/delete/list/describe topics`

**Comment by rigelbm** [comment]
These APIs have been added in Confluent Platform 6.0.0 (coming out soon!). You can see the spec here: https://github.com/confluentinc/kafka-rest/blob/6.0.x/api/v3/openapi.yaml#L372
