### ISSUE TITLE
http rest consumer 

### ISSUE THREAD

**Issue by HITxuefeng** [confluentinc/kafka-rest#352]
Return to 404 after a period of time，that's why!

**Comment by mageshn** [comment]
@HITxuefeng it not clear on what really the issue is? Are you asking about getting 404 on a consumer after some idle time? If so, we have the configuration that does this

consumer.instance.timeout.ms
Amount of idle time before a consumer instance is automatically destroyed.

Type: int
Default: 300000
Importance: low

**Comment by axisc** [comment]
@HITxuefeng , please feel free to open a new issue with relevant repro if you still see this issue.
