### ISSUE TITLE
"Consumer instance not found" when DELETE without providing Accept header

### ISSUE THREAD

**Issue by grongor** [confluentinc/kafka-rest#593]
Hello,

I noticed a strange behavior which I consider a bug: when you issue a DELETE request on a consumer instance, and you don't provide a correct Accept header, then you receive the error "Consumer instance not found.". I think that the header shouldn't matter here and the instance should be deleted without any issue, but if you think that the header is needed, then I would argue that the error message should say something about that (and not something seemingly irrelevant). I spent a good hour trying to figure out why I can't delete consumers right after I create them... 

I'm using the most recent REST Proxy (tar downloaded from Confluent web) with Confluent cloud.
```
curl -X POST "http://localhost:8082/consumers/grp" -H "Content-Type: application/vnd.kafka.json.v2+json" --data '{"name":"new-instance"}'
{"instance_id":"new-instance","base_uri":"http://localhost:8082/consumers/grp/instances/new-instance"}

$ curl -X DELETE http://localhost:8082/consumers/grp/instances/new-instance
{"error_code":40403,"message":"Consumer instance not found."}

$ curl -X DELETE -H "Accept: application/vnd.kafka.v2+json" http://localhost:8082/consumers/grp/instances/new-instance
// success
```

**Comment by karsov** [comment]
From my experience there is distinction between v1 and v2 consumers in kafka-rest and when you don't specify the content type the rest proxy assumes it is v1 (application/vnd.kafka.json.v1+json). So in your example:
  - you create a v2 consumer
  - you try to delete a v1 consumer (unsuccessfully because it does not exist)
  - you try to delete the v2 consumer (this one exists and is successfully deleted)

**Comment by grongor** [comment]
Oh, that would make sense. Unfortunately, it's really confusing, even though it at least makes sense now :/
