### ISSUE TITLE
kafka-rest java Heap space issue

### ISSUE THREAD

**Issue by varun-tangoit** [confluentinc/kafka-rest#594]
Hi,

I'm currently implementing kafka_rest proxy in ec2 instance for aws managed kafka. I got error like 
ERROR Uncaught exception in thread 'kafka-admin-client-thread | adminclient-1': (org.apache.kafka.common.utils.KafkaThread:51)
java.lang.OutOfMemoryError: Java heap space

Eventhough i improved or set environment variable, can't able to get result of list topics for that below curl;
curl "http://localhost:8082/topics"
export KAFKA_HEAP_OPTS="-Xms512m -Xmx1g"

can you please help me, how can i resolve this issue.

**Comment by danielsinai** [comment]
try KAFKAREST_HEAP_OPTS instead :)

source bin/kafka-rest-run-class:
`  exec $JAVA **$KAFKAREST_HEAP_OPTS** $KAFKAREST_JVM_PERFORMANCE_OPTS $KAFKAREST_JMX_OPTS $KAFKAREST_LOG4J_OPTS -cp $CLASSPATH $KAFKAREST_OPTS "$MAIN" "$@"
`

**Comment by ldicarlo** [comment]
Shouldn't it be `CONNECT_`+`HEAP_OPTS` as stated [here](https://docs.confluent.io/3.1.1/cp-docker-images/docs/configuration.html#kafka-connect) ?

**Comment by ldicarlo** [comment]
Shouldn't it be `KAFKA_REST` + `_HEAP_OPTS` as stated [here](https://docs.confluent.io/3.1.1/cp-docker-images/docs/configuration.html#kafka-rest-proxy) ?

**Comment by ldicarlo** [comment]
Oh, actually on Kafka connect for example, it is taken in account only if I pass `KAFKA_HEAP_OPTS`, I think

**Comment by psalot** [comment]
I had come across the same issue but for me the reason was incomplete configuration for connecting to kafka brokers.
This error occurs even if any of your configuration mismatch has happened.So first validate if your kafka instance has any authentication/authorization enabled. 
In my case TLS was enabled so I had to pass client.security.protocol=SSL and client.ssl.truststore.location={file path to trust store} property.
