### ISSUE TITLE
KAFKA_OPTS

### ISSUE THREAD

**Issue by quangvuptit** [confluentinc/kafka-rest#602]
How can I use this variable **`KAFKA_OPTS`** ?

**Comment by danielsinai** [comment]
Hi,
as you can see at bin/kafka-rest-run-class
there is this block code: 
`# Generic jvm settings you want to add
if [ -z "$KAFKAREST_OPTS" ]; then
  KAFKAREST_OPTS=""
fi
`

and after that
  exec $JAVA $KAFKAREST_HEAP_OPTS $KAFKAREST_JVM_PERFORMANCE_OPTS $KAFKAREST_JMX_OPTS $KAFKAREST_LOG4J_OPTS -cp $CLASSPATH $KAFKAREST_OPTS "$MAIN" "$@"

So that means you should pass KAFKAREST_OPTS as environment variable before the execution of the kafkarest server.

Good luck hope that helps :)

**Comment by quangvuptit** [comment]
> Hi,
> as you can see at bin/kafka-rest-run-class
> there is this block code:
> `# Generic jvm settings you want to add if [ -z "$KAFKAREST_OPTS" ]; then KAFKAREST_OPTS="" fi `
> 
> and after that
> `exec $JAVA $KAFKAREST_HEAP_OPTS $KAFKAREST_JVM_PERFORMANCE_OPTS $KAFKAREST_JMX_OPTS $KAFKAREST_LOG4J_OPTS -cp $CLASSPATH $KAFKAREST_OPTS "$MAIN" "$@"`
> 
> So that means you should pass KAFKAREST_OPTS as environment variable before the execution of the kafkarest server.
> 
> Good luck hope that helps :)

Thank you so much!
