### ISSUE TITLE
Not possible to advertise a port when behind a load balancer listening on default scheme ports (80,443)

### ISSUE THREAD

**Issue by imriz** [confluentinc/kafka-rest#758]
Hi,

We're running Kafka REST as an ECS Fargate task. The tasks sites behind an ALB, which listens on port 80, while the container listens on port 8082.
Even though we're setting advertised.listeners, the base_uri is returned without a port.
I believe this is because of: https://github.com/confluentinc/kafka-rest/blob/d29d91364e49f4865a91214dc46caab1826984be/kafka-rest/src/main/java/io/confluent/kafkarest/UriUtils.java#L38

Since the Host header from the ALB won't contain a port when the port used is the default for the protocol (per RFC), the advertised port is never used. We of course can make the ALB listen on non standard port so the port will be included, but this seems like it should work even without this workaround.

**Comment by rigelbm** [comment]
Hi @imriz. I'm assuming you are using Consume V2 API. That API (currently) does not respect the `advertised.listeners` config. There's a PR (https://github.com/confluentinc/kafka-rest/pull/768) to make that so in 6.1.0. The API you are using uses the `host.name` and `port` config. Unfortunately you are correct that, if the incoming request does not include port, than `port` won't be used. This is a behaviour that we can change, due to backwards compatibility. But if you use 6.1.0, just use `advertised.listeners`, and the behaviour should be correct.

**Comment by imriz** [comment]
@rigelbm This somehow got lost in the endless pit called my inbox 🤦  

Thank you so much for the quick response and solution!
