### ISSUE TITLE
Accept plain application/json for producers

### ISSUE THREAD

**Issue by RalfJL** [confluentinc/kafka-rest#759]
Hi,
apologies if I had missed out some issues or documentation.
If I understand that document right
https://docs.confluent.io/current/kafka-rest/api.html
the REST proxy accepts not only  application/vnd.kafka.binary.v2+json but should also accept application/json as content type.
Unfortunately that does not work:
curl -X POST -H "Content-Type: application/vnd.kafka.json.v2+json" --data '{"records":[{"value":{"name": "testUser"}}]}' "http://localhost:8082/topics/Radius"
succeeds, but:
curl -X POST -H "Content-Type: application/json" --data '{"records":[{"value":{"name": "testUser"}}]}' "http://localhost:8082/topics/Radius"
gives you a 
{"error_code":415,"message":"HTTP 415 Unsupported Media Type"}

How can I enable the REST proxy to accept application/json as content type?

Background:
We are trying to to send accounting request from Freeradius 3.x via rest module to Kafka. Unfortunately the rest module can only send application/json as content header. Patching the Freeradius source to send application/vnd.kafka.json.v2+json instead works, but, for support reasons, we are stuck with the version that comes with the OS. So patching is no option.

**Comment by MarkC0x** [comment]
Hi @RalfJL,

I believe the problem you are seeing is because of the following caveat when using `application/json`:

```
In all cases, if the embedded format is omitted, "binary" is assumed.
```

In your Produce `CURL` command you are passing in `JSON` as the embedded data (not binary), hence the command is failing.  If you used the following command (embedding binary data), it should work:

```
curl -X POST -H "Content-Type: application/json" --data '{"records":[{"value":"S2Fma2E="}]}' "http://localhost:8082/topics/Radius"
```

I would, however, suggest following the documentation which advises being more explicit with `content-type`:

```
Although using these less specific values is permitted, to remain compatible with future versions you should specify preferred content types in requests and check the content types of responses.
```

Cheers
Mark

**Comment by RalfJL** [comment]
Hi Mark,
thanks for your prompt reply.
Unfortunately the curl command that you suggest still produces the same error:
{"error_code":415,"message":"HTTP 415 Unsupported Media Type"}

Coming back to my problem of using the Freeradius REST module to connect to the REST proxy. The Freeradius REST module gives me only very limited choices. I totally agree with you that a client should be very specific about the data it sends. Looking at all the features the REST proxy offers, it might be absolutely necessary.
The Freeradius REST module though is a very simple REST client. Currently I do not see any way of checking the answer of the REST proxy, beside the return code, which is interpreted by the Freeradius REST module itself. 

So what do you think? Can a very simple REST client with limited abilities be a producer for Confluent REST proxy?
Adding the necessary patches to Freeradius REST module (add new specific header, check the answer for errors) might not be feasible in time. 

Many Thanks
Ralf

**Comment by MarkC0x** [comment]
Hi @RalfJL,

That's really strange, as I have just tried the exact same command on my local setup and it worked:

```
➜  confluent-5.5.2 curl -X POST -H "Content-Type: application/json" --data '{"records":[{"value":"S2Fma2E="}]}' "http://localhost:8082/topics/Radius"

{"offsets":[{"partition":0,"offset":0,"error_code":null,"error":null}],"key_schema_id":null,"value_schema_id":null}
```

Which version of REST Proxy are you running (mine is the latest `CP 5.5.2` version)?

Cheers
Mark

**Comment by RalfJL** [comment]
Hi Mark,

mine is the newest one
confluent-kafka-rest/stable,now 6.0.0-1
Do I have the wrong version?

Cheers
Ralf

**Comment by MarkC0x** [comment]
Hi @RalfJL,

OK, I believe that explains the behavior you are seeing.

If you don't specify an API Version in your `Content-Type` header (you are just supplying `application/json`) then the most recent stable version will be used.  When REST Proxy moved to version `6.0.0` the latest stable API Version moved from `v2` up to `v3`.  Currently the `v3` API supports Cluster, Broker, Topic, etc. administration functions, and not Produce or Consume functions yet (although these are on the roadmap) -- hence the error when you try and Produce.

I think this leaves you with a couple of options:

1. Use the `5.2.2` version of REST Proxy (Brokers etc. can remain on `6.0`), where the following command will work as expected (since the API Version will default to `v2`) which binary embedded messages:

```
curl -X POST -H "Content-Type: application/json" --data '{"records":[{"value":"S2Fma2E="}]}' "http://localhost:8082/topics/Radius"
```

2. If you want to use the `6.0` version of REST Proxy then you will need to be explicit in your `Content-Type` header (see below).  This will be true until the `v3` API supports Produce functionality.

```
curl -X POST -H "Content-Type: application/vnd.kafka.json.v2+json" --data '{"records":[{"value":{"name": "testUser"}}]}' "http://localhost:8082/topics/Radius"

or

curl -X POST -H "Content-Type: application/vnd.kafka.binary.v2+json" --data '{"records":[{"value":"S2Fma2E="}]}' "http://localhost:8082/topics/Radius"
```

Although, the above `Content-Type` header may not be possible, as you mentioned previously.

Hope this helps?

Cheers
Mark

**Comment by RalfJL** [comment]
Hi Mark,
thanks for your efforts. There will still be the pain of teaching Freeradius Server to fill all the gaps.
So we decided to go with the PERL module of Freeradius and the PERL library for Kafka. That not only gives us more control over the Data to be sent but also more control on buffering and error handling. We found that the REST module of Freeradius blocks the server if the connection to Kafka-proxy is lost. In our case, where accounting data is for monitoring only, it is not acceptable.
Another benefit is KIS (keep it simple). We just save one more process or say "the chain is one link shorter".

So thanks again. Cheers
Ralf
