### ISSUE TITLE
Long polling or web sockets

### ISSUE THREAD

**Issue by mpj** [confluentinc/kafka-rest#76]
Am I correct to understand that I can't really use this proxy to actually subscribe to a topic and get messages as they arrive? That's pretty sad.

I think it would be pretty great if you could use web sockets or long polling to provide the ability to consume a stream as messages come in.

**Comment by ewencp** [comment]
The proxy does support subscribing to and consuming messages as they arrive. See the consumers section of the documentation: http://confluent.io/docs/current/kafka-rest/docs/api.html#consumers The quickstart shows how to do this with curl: http://confluent.io/docs/current/kafka-rest/docs/intro.html#quickstart

However, since one HTTP request per message would be a lot of overhead, we try to batch messages together when possible. Take a look at the consumer.request.max.bytes and consumer.request.timeout.ms settings http://confluent.io/docs/current/kafka-rest/docs/config.html If your use case has low enough throughput on the topic, you could adjust those settings to ensure you receive messages with lower latency.

**Comment by edoard** [comment]
Hi, just for clarification,
the rest client has to make new http requests to recieve new messages, 
it cannot receive them with log polling, right ?

many thanks

**Comment by ewencp** [comment]
@edoard You can control the behavior with the `consumer.request.max.bytes` and `consumer.request.timeout.ms` settings. If you want long polling behavior, you can set `consumer.request.max.bytes` to a smaller value and `consumer.request.timeout.ms` to a very large value. By setting the timeout very large, you will wait effectively indefinitely for new data. By setting the maximum number of bytes to a smaller value you avoid batching up more messages.

If these settings don't give the kind of control you want, I'm open to additional controls. For example, one issue with these settings is that if you set the max bytes small enough to promptly trigger a response, this also means you won't generate responses with batches of data larger than that, even if there is already enough data available. One option would be to add a consumer.request.min.bytes as well. Then responses could be triggered either if you hit that minimum or hit the timeout. By default we'd make it match the current behavior (that "minimum" would effectively be infinite), but if you overrode it to 0, then I think it would give you exactly the long polling behavior you want since as soon as any data was available it would be returned but could still include any more messages that are already available.

**Comment by edoard** [comment]
Thanks!

**Comment by edoard** [comment]
Trying this out, I see that not only the consumer.request.min.bytes would be very welcome, 
but also it would be great if these settings could be set to indiviidual consumers when they are created, not globally

**Comment by marekstachura** [comment]
Hi @edoard,
we've been trying to get the long polling behaviour working, unfortunately without any success.

We tried following scenario:
- we set the consumer.request.max.bytes to something relative low (1Mb)
- we set the consumer.request.timeout.ms to something relative high (60 seconds)
- we create a log polling request to consume the messages from a topic
- after we created the request to consume the messages from a topic we started to produce the messages - produce 10 messages, sleep for 1 second, produce 10 messages sleep for one second, etc.
- we were expecting to see that the previous opened connection to Kafka REST to consume the messages would receive the messages we produce, unfortunately we have not received them until we restarted the connection - basically the connection timed out after 60 seconds and we created new one which received all messages created previously.

We are consuming the messages from C# and the code for consuming as long polling is similar to that example: https://gist.github.com/marekstachura/2941d7dbd80f82c92af9

What we need is as low latency as possible - between producing and consuming applications.
At the moment we changed the consumer.request.timeout.ms to 100 milliseconds and we are consuming the messages every 100 milliseconds... This is not great solution as it has quite massive impact on CPU usage and the number of connections made from Kafka REST to Zookeeper. We had to change the maxClientCnxns in Zookeeper config as Zookeeper was blocking the connections from our Kafka REST instances.

So, my question is - do you have any examples where we can see the long polling is working fine for Kafka REST?
Is there anything else we could try to get the lowest possible latency between our producing and consuming applications using Kafka REST?

Thanks,
Marek

**Comment by ewencp** [comment]
@marekstachura I think you probably want the `consumer.request.min.bytes` option, which is not yet implemented.

For your example, is 1 Mb for `consumer.request.max.bytes` actually low? You mentioned 10 messages followed by sleeping 1 second, followed by 10 more. For those first 10 to get returned, they'd each have to be 100Kb. This isn't very large, but many people have smaller messages than that so I want to make sure the test is actually expected to return data.

However, if the connection is actually timing out without returning data, that sounds like a bug. Do you have a complete test case that reproduces the issue that you could post to another issue?

You also mentioned an issue with Zookeeper connections. If the REST proxy specifically is causing you to hit connection limits unexpectedly, could you file another bug for that? As far as I know each instance should only use one connection in the REST proxy code and only one connection per client (with only a couple of producers per REST proxy instance and as many consumers as you keep alive at a time, taking into account `consumer.instance.timeout.ms`). So if REST proxy instances are causing you to hit connection limits, that probably indicates a bug.

**Comment by marekstachura** [comment]
Hi @ewencp,

thanks for your reply.

regarding the ``consumer.request.max.bytes`` I set it to be 1Mb and every message I sent was nearly 1Mb as well, it would mean the consumer should receive the messages let's say after every second message.
I'll try to create a test case for that and will let you know.

Regarding Zookeeper connections - the same, I'll create a test case.

Thanks,
Marek

**Comment by pltchuong** [comment]
Sorry for digging up this topic one more time. I have looking around but still couldn't figure out the answer for similar question: Can I send **one request** from my web application to `kafka-rest` and expected a response from consumer (which is Spark Streaming in my case)? Or should I have to keep sending another request**s** to `kafka-rest` to wait for the response?

Regards,
-- Phan

**Comment by jonefeewang** [comment]
anyone has this question could follow thread #470

**Comment by nickvgils** [comment]
For a consumer group, i'm having 326 Total Messages behind. Currently having `consumer.request.timeout.ms` to a very large value and `consumer.request.max.bytes` at default doesn't trigger anything which makes sense because the default max bytes isn't reached with 326 messages. When putting `fetch.min.bytes` at 0, i am expecting all the 326 messages to be returned by the REST call, but it doesn't. It returns only 30 messages. What is this 30 messages based upon? When raising `consumer.request.max.bytes` nothing changes so it isn't because of this config.
