### ISSUE TITLE
Support for JSON messages

### ISSUE THREAD

**Issue by jpblair** [confluentinc/kafka-rest#79]
I was wondering if there was any possibility of adding support for messages in formats beyond just Avro/Base64.  For my use case (and likely many others), only strings are passed back and forth, so encoding to Base64 seems like overkill.  Having to encode in Base64 isn't a huge pain point, but just seems unnecessary.  Apologies if this is already supported and I just didn't find it in the documentation since I just started working with this today!  Looks like it will be quite useful regardless.  :)

**Comment by ewencp** [comment]
@jpblair Sure, we're certainly not opposed to supporting more formats. Another one that I would guess is in higher demand is JSON. Strings also need some careful handling -- you need to be sure to handle encoding properly so downstream consumers get the string in the format they expect. Currently I think we'd have to have that be a global property for the entire REST proxy, at least for produce requests, because we limit to 1 producer per serializer type.

Adding support for a new type isn't trivial, but only has a few key places you need to add code. We'd need to add a new value to the EmbeddedType enum, introduce new constants for the Accept/Content-Type headers and update annotations on the TopicResource, PartitionsResource, and ConsumersResource. Then add corresponding methods for Strings, e.g. below consumeBinary and consumeAvro in PartitionsResource. From there, you just have to chase down the couple of points where data is converted, such as in AvroConsumerState. And of course, a bunch of tests :)

(Just as an aside, I'd highly discourage using plain strings unless you have really trivial data that you're absolutely certain won't need to evolve in format. Otherwise you'll eventually end up with ad hoc serializers and parsers throughout your code.)

**Comment by jpblair** [comment]
Yes, the data I want to send is in JSON.  Again, not a major issue since I can always encode to Base64, was just wondering if it would be unnecessary overhead.

**Comment by ewencp** [comment]
Ah, ok, then we're probably better off just supporting JSON directly -- in most cases it'll be simpler for the application if they can embed the JSON directly in the request payload (or get it already parsed from the response payload for consumption).

**Comment by ottomata** [comment]
+1 this would be handy :)

**Comment by hachikuji** [comment]
Just merged a patch with JSON message support. See #89 for implementation details.
