### ISSUE TITLE
Empty message array when creating consumer followed by immediate read

### ISSUE THREAD

**Issue by cwscribner** [confluentinc/kafka-rest#84]
I'm working on a simple web ui to read messages from a topic so my colleagues don't need to issue curl requests by hand.  While futzing around with the code, I noticed that if I create a consumer on every page visit (in the same consumer group) I hit a upper bound where I can continue creating consumers and reading from the topic but cannot get any messages from the topic.  Simply waiting a while seems to clear this condition.

Consumers are created using this data: `{"format": "binary", "auto.offset.reset": "smallest"}`

The process is something like this on page visit:

1. Create consumer in mygroup
2. Read from mytopic
3. Messages retrieved
4. Refresh page in an attempt to get the new messages (Repeats 1 & 2)
5. Empty array returned even though I'm using a new consumer

Am I missing some finer point of consumers/consumer groups?

**Comment by ewencp** [comment]
Consumers are generally expected to be long lived, and high level consumers will be relatively expensive to create (since they require interacting with ZK to track their state). This is independent of kafka-rest, it's just the way Kafka consumers/consumer groups work.

Additionally, consumers may have a short startup delay during setup before they are fully setup, have agreed on partition balancing (for consumer groups with multiple consumers), have fetched the metadata they need, and then finally have actually started fetching messages. Since read requests only wait 1s by default in kafka-rest, it might just be that it's taking longer to get everything setup than the first request waits for data. One option would be to increase that timeout, but I'm not sure that's really a good solution.

The alternative would be to allow clients to reuse the same consumer across multiple page views. Maybe save a cookie with the random ID, or even just use some client-specific info to generate a unique ID on demand. One drawback to this approach is that the offset reset won't happen for each page load, so you wouldn't get to see old data.

It is committed but hasn't been released yet, but you might be interested in this patch: https://github.com/confluentinc/kafka-rest/pull/66 It adds simple consumer functionality, which might make more sense for your use case?

**Comment by cwscribner** [comment]
Yeah it looks like that patch may be of help.  Like you said, the issue with the cookie is that the offset reset doesn't happen and we need to be able to see the old messages as well.  Any ETA on when SimpleConsumer will get released?

**Comment by ewencp** [comment]
No ETA yet on a release, but if you're comfortable building it (and dependencies) yourself you can build an uber jar version using `mvn package -P standalone`.

Other than that, is there anything we should be fixing in this bug still or would the simple consumer API address your problem? It sounds like this is just an issue with the underlying consumer that you weren't expecting.

**Comment by cwscribner** [comment]
As of right now I think the simple consumer would do the trick so I'll close this issue.  I think I have a workaround for the issue by caching the consumer base_uri and the most recent messages and displaying those if there are no new messages.  Thanks for the assistance!
