### ISSUE TITLE
Ephemeral node loop

### ISSUE THREAD

**Issue by cwscribner** [confluentinc/kafka-rest#86]
Feel free to close if this is addressed elsewhere, but I ran into an issue recently that manifested in the Kafka REST Proxy logs identical to the behavior here: [KAFKA-1387](https://issues.apache.org/jira/browse/KAFKA-1387)

Are the error messages I'm seeing just pass through from the consumer or is this specific to Kafka REST Proxy?  In either case, is there a fix present?

Kafka Version: 0.8.2-beta

**Comment by ewencp** [comment]
The proxy uses the Kafka Java clients internally, so you should see logs from them. You'll see whatever the log4j config you're running with is configured to log, see, e.g. https://github.com/confluentinc/kafka-rest/blob/master/config/log4j.properties

That said, it looks like the bug you're referring to is for the broker? You shouldn't expect to see broker logs since we only use the clients (new producer, old consumer).

**Comment by cwscribner** [comment]
Is it impossible to see broker logs in the kafka-rest logs or just unlikely?

The message I see for kafka-rest is this: `INFO I wrote this conflicted ephemeral node **** a while back in a different session, hence I will backoff for this node to be deleted by Zookeeper and retry` which was really my only reason for linking that issue.

**Comment by ewencp** [comment]
Ah, this message is from a general ZK utility function. The consumer uses this when registering itself in zookeeper with its ID. You'll probably find "begin registering consumer <consumer ID> in ZK" right before this message.

My guess is that you've got conflicting consumer IDs. There was an issue related to this and it's fixed in master (but not yet released): https://github.com/confluentinc/kafka-rest/pull/67 Are you running multiple REST proxy instances against the same cluster? If so, have you set a unique ID in the `id` config for each instance? If you haven't and you're using server-generated automatically incrementing IDs, you may be getting consumer instance ID conflicts from different REST proxy instances.

The patch for that issue should make things easier to manage in future versions -- then the default behavior if you don't specify IDs will use UUIDs, which should provide the behavior most people expect since those should be globally unique.

**Comment by cwscribner** [comment]
Yeah that's exactly what it is; conflicting consumer IDs.  I found a way around the issue I had in #84 by creating and destroying the consumer on page request.  I bet that if the DELETE doesn't happen properly it'll try to recreate a consumer with the same ID.  Not super efficient but aside from this, I haven't had any other problems.  Thanks for the help!
