### ISSUE TITLE
Prometheus metrics coming unexpectedly for deleted kafka connectors.

### ISSUE THREAD

**Issue by akshay-agarwal-17** [confluentinc/kafka-rest#999]
We created few connectors, but when we delete them , we observe that few of them even after getting deleted are producing metrics. 

Steps to reproduce - 
1 . Create 20 connectors. 

[Put connectors](https://docs.confluent.io/platform/current/connect/references/restapi.html#put--connectors-(string-name)-config)

2. Delete 20 connectors.

[Delete connectors](https://docs.confluent.io/platform/current/connect/references/restapi.html#delete--connectors-(string-name)-)

3. Confirm that status for all the connectors is - 

`{
    "error_code": 404,
    "message": "No status found for connector test_connector"
}`

[Connector Status](https://docs.confluent.io/platform/current/connect/references/restapi.html#get--connectors-(string-name)-status)

Now few connectors don't get deleted from pods, and continue to export metrics to prometheus.

Workaround that we are currently using - We restart the pods, and the deleted connectors are flushed during restart.

Can we avoid pod restart by having some enhanced garbage collection mechanism.

**Comment by dimitarndimitrov** [comment]
Hey @akshay-agarwal-17,

You are talking about the [Kafka Connect REST API](https://docs.confluent.io/platform/current/connect/references/restapi.html), which is [part of Apache Kafka](https://github.com/apache/kafka/tree/8047ba3800436d6162d0f8eb707e28857ab9eb68/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/rest) and is different from the Kafka REST API provided by this repo.
I'd suggest to follow up by reporting this in a Kafka JIRA.

P.S. The problem you are reporting seems related to [KAFKA-7726](https://issues.apache.org/jira/browse/KAFKA-7726), although that issue is pretty old so I'm not sure if it's still relevant.
